# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [2]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

import numpy as np

# Let's define a one-dimensional array 
list_1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
list_1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [2]:
# Let's create a numpy array from the list "my_list"
my_numpy_array = np.array(list_1)
my_numpy_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
type(my_numpy_array)

numpy.ndarray

In [4]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array([[1, 2, 3], [10, 20, 30], [100, 200, 300]])
my_matrix

array([[  1,   2,   3],
       [ 10,  20,  30],
       [100, 200, 300]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [5]:
challenge_matrix = np.array([[3, 7, 9 ,3], [4, 3, 2, 2]])
challenge_matrix

array([[3, 7, 9, 3],
       [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [6]:
# "rand()" uniform distribution between 0 and 1
random_values = np.random.rand(25)
random_values

array([0.41424585, 0.8962865 , 0.6925594 , 0.12212693, 0.1741525 ,
       0.03668057, 0.70970127, 0.37665337, 0.76991211, 0.51058023,
       0.3602888 , 0.34713444, 0.27602132, 0.11590097, 0.30253509,
       0.47594874, 0.06143449, 0.46134305, 0.0176441 , 0.26862929,
       0.69349532, 0.4667324 , 0.11910181, 0.76760872, 0.2190625 ])

In [7]:
# you can create a matrix of random number as well
random_matrix = np.random.rand(5, 5)
random_matrix

array([[0.43594678, 0.67768387, 0.23838106, 0.72723006, 0.37106079],
       [0.90769496, 0.26051216, 0.58353684, 0.52012175, 0.87071696],
       [0.82257847, 0.77346885, 0.23992962, 0.00211613, 0.30456013],
       [0.45688233, 0.48324588, 0.52667923, 0.45255712, 0.47407671],
       [0.53967363, 0.93292438, 0.93282566, 0.81366969, 0.41566501]])

In [26]:
# "randint" is used to generate random integers between upper and lower bounds
random_integer = np.random.randint(1, 21) # this is between 1 and 20!!!
random_integer

16

In [72]:
# fun little program by Matt :)
# keep generating random numbers between 1 & 100 and stop when you get a 100
random_integer = np.random.randint(1, 101)

while random_integer != 100:
    print(random_integer)
    random_integer = np.random.randint(1, 101)

print(random_integer, "Stop")

93
75
60
34
24
31
51
7
100 Stop


In [10]:
# "randint" can be used to generate a certain number of random itegers as follows
five_random = np.random.randint(1, 100, 5)
five_random

array([27, 20, 80, 19, 54])

In [36]:
# np.arange creates an evenly spaced values within a given interval
evenly = np.arange(1, 26)
evenly

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [37]:
# create a diagonal of ones and zeros everywhere else
diagonal = np.eye(7)
diagonal

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [39]:
# Matrix of ones
matrix_of_ones = np.ones((7, 10))
matrix_of_ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [41]:
# Array of zeros
array_of_zeros = np.zeros(5)
array_of_zeros

array([0., 0., 0., 0., 0.])

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [22]:
user_input = int(input("Enter a positive integer:"))

random_integer_array = np.random.randint(1, user_input, 10)

random_integer_array


Enter a positive integer:2


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [75]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1, 11)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
y = np.arange(1, 11)
y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [78]:
# Add 2 numpy arrays together
sum = x + y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [81]:
multiply = x * 2
multiply

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [82]:
square = x ** 2
square

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [83]:
square_root = np.sqrt(square)
square_root

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [84]:
z = np.exp(y) # exponential
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [90]:
x = np.array([5, 7, 20])
y = np.array([9, 15, 4])

z = np.sqrt(x ** 2 + y **2 )
z

array([10.29563014, 16.55294536, 20.39607805])

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [4]:
my_array = np.array([3, 2, 7, 4, 8, 9, 5 ,4])
my_array

array([3, 2, 7, 4, 8, 9, 5, 4])

In [7]:
# Access specific index from the numpy array
print(my_array[0])
print(my_array[-1])

3
4


In [15]:
# Starting from the first index 0 up until and NOT including the last element
my_array[0:4] # this is not including the fourth value (first one has index 0)

array([3, 2, 7, 4])

In [16]:
# Broadcasting, altering several values in a numpy array at once
my_array[0:4] = 9
my_array

array([9, 9, 9, 9, 8, 9, 5, 4])

In [17]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1, 10, (4,5)) # first random numbers between 1 and 10 and then matrix size
matrix

array([[7, 7, 4, 5, 6],
       [7, 6, 1, 6, 8],
       [6, 8, 8, 4, 5],
       [8, 6, 2, 1, 4]])

In [18]:
# Get a row from a mtrix
matrix[0]

array([7, 7, 4, 5, 6])

In [26]:
# Get one element
print(matrix[3, 3]) # OR
print(matrix[3][3])

1
1


MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [31]:
x = np.array([[2, 30, 20, -2, -4],
              [3, 4, 40, -3, -2], 
              [-3, 4, -6, 90, 10], 
              [25, 45, 34, 22, 12], 
              [13, 24, 22, 32, 37]])
x[4] = 0
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [32]:
matrix = np.random.randint(1, 10, (5, 5))
matrix

array([[7, 1, 3, 9, 4],
       [1, 8, 4, 6, 3],
       [1, 4, 1, 8, 1],
       [7, 8, 8, 6, 3],
       [7, 2, 5, 5, 2]])

In [38]:
filter_by_number = matrix[matrix > 7]
filter_by_number

array([9, 8, 8, 8, 8])

In [40]:
# Obtain odd elements only
filter_odd = matrix[matrix % 2 == 1] # remainder after division
filter_odd

array([7, 1, 3, 9, 1, 3, 1, 1, 1, 7, 3, 7, 5, 5])

In [47]:
# Even elements only
filter_even = matrix[matrix % 2 == 0] # no remained after division by 2
filter_even

array([4, 8, 4, 6, 4, 8, 8, 8, 6, 2, 2])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [52]:
X = np.array([[2, 30, 20, -2, -4],
              [3, 4,  40, -3, -2],
              [-3, 4, -6, 90, 10],
              [25, 45, 34, 22, 12],
              [13, 24, 22, 32, 37]])
X[X < 0] = 0
X[X % 2 == 1] = -2
X

array([[ 2, 30, 20,  0,  0],
       [-2,  4, 40,  0,  0],
       [ 0,  4,  0, 90, 10],
       [-2, -2, 34, 22, 12],
       [-2, 24, 22, 32, -2]])

# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [ ]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [53]:
import pandas as pd

In [55]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
bank_client_df = pd.DataFrame({"Bank Client ID": [101, 202, 303, 404],
                              "Bank Client Name": ["Matt", "James", "Sophia", "Andy"],
                              "Net Worth [$]": [3500, 4000, 20000, 400000],
                              "Years with bank": [5, 6, 8, 4]})
bank_client_df

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             101             Matt           3500                5
1             202            James           4000                6
2             303           Sophia          20000                8
3             404             Andy         400000                4

In [57]:
# Let's obtain the data type 
type(bank_client_df)

pandas.core.frame.DataFrame

In [60]:
# you can only view the first couple of rows using .head()
bank_client_df.head(2)

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
0             101             Matt           3500                5
1             202            James           4000                6

In [61]:
# you can only view the last couple of rows using .tail()
bank_client_df.tail(2)

Bank Client ID Bank Client Name  Net Worth [$]  Years with bank
2             303           Sophia          20000                8
3             404             Andy         400000                4

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [63]:
portfolio_df = pd.DataFrame({"Stock": ["AAPL", "AMZN", "INTC"],
                              "Number of Shares": [40, 84, 420],
                              "Price per Share [$]": [45, 34, 12],})
portfolio_df

Stock  Number of Shares  Price per Share [$]
0  AAPL                40                   45
1  AMZN                84                   34
2  INTC               420                   12

In [68]:
stock_value = portfolio_df["Price per Share [$]"] * portfolio_df["Number of Shares"]
print(stock_value)

print(stock_value.sum())

0    1800
1    2856
2    5040
dtype: int64
9696


# TASK #7: PANDAS WITH CSV AND HTML DATA

In [77]:
# Pandas is used to read a csv file and store data in a DataFrame
house_price_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')
house_price_df[0]

City  \
0                                      Vancouver, BC   
1                                       Toronto, Ont   
2                                        Ottawa, Ont   
3                                       Calgary, Alb   
4                                      Montreal, Que   
5                                        Halifax, NS   
6                                       Regina, Sask   
7                                    Fredericton, NB   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                 Average House Price  \
0                                         $1,036,000   
1                                           $870,000   
2                                           $479,000   
3                                           $410,000   
4                                           $435,000   
5                                           $331,000   
6                                           $254,000   
7                                           $198,000   
8  (adsbygoogle = window.adsbygoogle || []).push(...   

                                     12 Month Change  
0                                           + 2.63 %  
1                                            +10.2 %  
2                                           + 15.4 %  
3                                            – 1.5 %  
4                                            + 9.3 %  
5                                            + 3.6 %  
6                                            – 3.9 %  
7                                            – 4.3 %  
8  (adsbygoogle = window.adsbygoogle || []).push(...

In [78]:
house_price_df[1]

Province  \
0                                    British Columbia   
1                                             Ontario   
2                                             Alberta   
3                                              Quebec   
4                                            Manitoba   
5                                        Saskatchewan   
6                                         Nova Scotia   
7                                Prince Edward Island   
8                             Newfoundland / Labrador   
9                                       New Brunswick   
10                                   Canadian Average   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                  Average House Price  \
0                                            $736,000   
1                                            $594,000   
2                                            $353,000   
3                                            $340,000   
4                                            $295,000   
5                                            $271,000   
6                                            $266,000   
7                                            $243,000   
8                                            $236,000   
9                                            $183,000   
10                                           $488,000   
11  (adsbygoogle = window.adsbygoogle || []).push(...   

                                      12 Month Change  
0                                             + 7.6 %  
1                                             – 3.2 %  
2                                             – 7.5 %  
3                                             + 7.6 %  
4                                             – 1.4 %  
5                                             – 3.8 %  
6                                             + 3.5 %  
7                                             + 3.0 %  
8                                             – 1.6 %  
9                                             – 2.2 %  
10                                            – 1.3 %  
11  (adsbygoogle = window.adsbygoogle || []).push(...

MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [80]:
table = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
table[0]

Year of birth  \
0                                      1937 and prior   
1                                                1938   
2                                                1939   
3                                                1940   
4                                                1941   
5                                                1942   
6                                             1943-54   
7                                                1955   
8                                                1956   
9                                                1957   
10                                               1958   
11                                               1959   
12                                     1960 and later   
13  Notes: 1. Persons born on January 1 of any yea...   

                                                  Age  
0                                                  65  
1                                     65 and 2 months  
2                                     65 and 4 months  
3                                     65 and 6 months  
4                                     65 and 8 months  
5                                    65 and 10 months  
6                                                  66  
7                                     66 and 2 months  
8                                     66 and 4 months  
9                                     66 and 6 months  
10                                    66 and 8 months  
11                                   66 and 10 months  
12                                                 67  
13  Notes: 1. Persons born on January 1 of any yea...

# TASK #8: PANDAS OPERATIONS

In [ ]:
# Let's define a dataframe as follows:


In [ ]:
# Pick certain rows that satisfy a certain criteria 


In [ ]:
# Delete a column from a DataFrame


MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

# TASK #9: PANDAS WITH FUNCTIONS

In [ ]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

In [ ]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 


In [ ]:
# You can apply a function to the DataFrame 


MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [ ]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})
bank_client_df

In [ ]:
# You can sort the values in the dataframe according to number of years with bank


In [ ]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True


In [ ]:
# Set inplace = True to ensure that change has taken place in memory 


In [ ]:
# Note that now the change (ordering) took place 


# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [ ]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

MINI CHALLENGE #1 SOLUTION: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [ ]:
x = np.array([[[3, 7, 9, 3] , [4, 3, 2, 2]]])
x

MINI CHALLENGE #2 SOLUTION:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 10)
x

MINI CHALLENGE #3 SOLUTION:
- Given the X and Y values below, obtain the distance between them


```
X = [5, 7, 20]
Y = [9, 15, 4]
```




In [ ]:
X = np.array([5, 7, 20])
Y = np.array([9, 15, 4])
Z = np.sqrt(X**2 + Y**2)
Z

MINI CHALLENGE #4 SOLUTION:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

MINI CHALLENGE #5 SOLUTION:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```

In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X<0] = 0
X[X%2==1] = -2
X

MINI CHALLENGE #6 SOLUTION:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [ ]:
portfolio_df = pd.DataFrame({'stock ticker symbols':['AAPL', 'AMZN', 'T'],
                             'price per share [$]':[3500, 200, 40], 
                             'Number of stocks':[3, 4, 9]})
portfolio_df

In [ ]:
stocks_dollar_value = portfolio_df['price per share [$]'] * portfolio_df['Number of stocks']
print(stocks_dollar_value)
print('Total portfolio value = {}'.format(stocks_dollar_value.sum()))

MINI CHALLENGE #7 SOLUTION:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [ ]:
# Read tabular data using read_html
retirement_age_df = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')
retirement_age_df

MINI CHALLENGE #8 SOLUTION:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [ ]:
df_high_networth = bank_client_df[ (bank_client_df['Net worth [$]'] >= 5000) ]
df_high_networth

In [ ]:
df_high_networth['Net worth [$]'].sum()

MINI CHALLENGE #9 SOLUTION:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [ ]:
def networth_update(balance):
    return balance * 3 + 200 

In [ ]:
# You can apply a function to the DataFrame 
results = bank_client_df['Net worth [$]'].apply(networth_update)
results

In [ ]:
results.sum()

PROJECT SOLUTION:

In [ ]:
# Creating a dataframe from a dictionary
# Let's define a dataframe with a list of bank clients with IDs = 1, 2, 3, 4, 5 

raw_data = {'Bank Client ID': ['1', '2', '3', '4', '5'],
            'First Name': ['Nancy', 'Alex', 'Shep', 'Max', 'Allen'], 
            'Last Name': ['Rob', 'Ali', 'George', 'Mitch', 'Steve']}

Bank_df_1 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_1


# Let's define another dataframe for a separate list of clients (IDs = 6, 7, 8, 9, 10)
raw_data = {
        'Bank Client ID': ['6', '7', '8', '9', '10'],
        'First Name': ['Bill', 'Dina', 'Sarah', 'Heather', 'Holly'], 
        'Last Name': ['Christian', 'Mo', 'Steve', 'Bob', 'Michelle']}
Bank_df_2 = pd.DataFrame(raw_data, columns = ['Bank Client ID', 'First Name', 'Last Name'])
Bank_df_2


# Let's assume we obtained additional information (Annual Salary) about our bank customers 
# Note that data obtained is for all clients with IDs 1 to 10 
raw_data = {
        'Bank Client ID': ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'],
        'Annual Salary [$/year]': [25000, 35000, 45000, 48000, 49000, 32000, 33000, 34000, 23000, 22000]}
bank_df_salary = pd.DataFrame(raw_data, columns = ['Bank Client ID','Annual Salary [$/year]'])
bank_df_salary


# Let's concatenate both dataframes #1 and #2
# Note that we now have client IDs from 1 to 10
bank_df_all = pd.concat([Bank_df_1, Bank_df_2])
bank_df_all


# Let's merge all data on 'Bank Client ID'
bank_df_all = pd.merge(bank_df_all, bank_df_salary, on = 'Bank Client ID')
bank_df_all


In [ ]:
new_client = {
        'Bank Client ID': ['11'],
        'First Name': ['Ry'], 
        'Last Name': ['Aly'],
        'Annual Salary [$/year]' : [1000]}
new_client_df = pd.DataFrame(new_client, columns = ['Bank Client ID', 'First Name', 'Last Name', 'Annual Salary [$/year]'])
new_client_df

In [ ]:
new_df = pd.concat([bank_df_all, new_client_df], axis = 0)
new_df